id: P0C5A4AEB
initial_creation_type: input
source_metadata:
  title: Buddhagupta
  language: en
  description: Instructions
  volume:
    3ff6b07ea108409495eceb4df4fd5f89:
      title: An Extensive Commentary on the Four Immeasurables
      parent: Instructions
created_at: '2022-03-01T02:13:36.519185'
last_modified_at: '2022-03-01T02:13:36.519191'
